### ISSUE TITLE
IllegalStateException thrown when clicking the "Confirm" button of the settings window

### ISSUE THREAD

**Issue by MrFouss** [MrFouss/The-Projects#58]
Exception in thread "Thread-3" java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = Thread-3
    at com.sun.glass.ui.Application.checkEventThread(Application.java:443)
    at com.sun.glass.ui.Window.isMaximized(Window.java:457)
    at com.sun.javafx.tk.quantum.WindowStage.setMaximized(WindowStage.java:546)
    at javafx.stage.Stage.setMaximized(Stage.java:823)
    at the_projects.view.View.setBoard(View.java:61)
    at the_projects.view.View.displayGameBoard(View.java:48)
    at the_projects.controller.Controller.run(Controller.java:52)

Thrown when View.setBoard is called at the line "setMaximized(true);"

**Comment by Th0re** [comment]
https://github.com/MrFouss/The-Projects/issues/59
